### ISSUE TITLE
 The project  is not opened in the workspace

### ISSUE THREAD

**Issue by qf28** [tsantalis/jdeodorant-commandline#12]
I am running jdeodorant from commandline on mac os. It shows the project is not opened in the workspace.

Where should i put the project? Thanks~

eclipse -pd workspace/avro/.project -x "clones.xls" -m PARSE_AND_ANALYZE
!SESSION 2019-02-26 15:16:21.355 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_112
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -pd workspace/avro/.project -x clones.xls -m PARSE_AND_ANALYZE
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -consoleLog -pd workspace/avro/.project -x clones.xls -m PARSE_AND_ANALYZE

!ENTRY org.eclipse.core.resources 2 10035 2019-02-26 15:16:22.250
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.
java.lang.RuntimeException: The project "avro-toplevel" is not opened in the workspace. Cannot continue.
	at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:172)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1519)

**Comment by tsantalis** [comment]
The arguments `-p` and `-pd` are relative to the workspace root
If project avro is inside /Users/qf28/workspace/avro
`-p avro`
`-pd "avro/.project"`
