### ISSUE TITLE
The project is not opened in the workspace

### ISSUE THREAD

**Issue by T45K** [tsantalis/jdeodorant-commandline#15]
related to #12 

I encountered the error reported in #12, but I think I specified the project dir correctly.
What's going on?

My environment: Mac OS Catalina
AdoptOpenJDK8
Target project: jFreeChart(https://github.com/jfree/jfreechart)

```
./eclipse -p jfreechart -x "./clone.xls" -m "PARSE_AND_ANALYZE" -t CLONE_TOOL_CCFINDER -i ... -xargs ...
!SESSION 2019-11-08 10:16:14.042 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_232
java.vendor=AdoptOpenJDK
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=ja_JP
Framework arguments:  -p jfreechart -x ./clone.xls -m PARSE_AND_ANALYZE -t CLONE_TOOL_CCFINDER -i ... -xargs ...
Command-line arguments:  -os macosx -ws cocoa -arch x86_64 -consoleLog -p jfreechart -x ./clone.xls -m PARSE_AND_ANALYZE -t CLONE_TOOL_CCFINDER -i ... -xargs ...

!ENTRY org.eclipse.core.resources 2 10035 2019-11-08 10:16:16.043
!MESSAGE The workspace exited with unsaved changes in the previous session; refreshing workspace to recover changes.
java.lang.RuntimeException: The project "jfreechart" is not opened in the workspace. Cannot continue.
	at ca.concordia.jdeodorant.eclipse.commandline.Application.getJavaProject(Application.java:950)
	at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:159)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:400)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:660)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:597)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1468)

!ENTRY org.eclipse.core.resources 2 10035 2019-11-08 10:16:17.228
!MESSAGE The workspace will exit with unsaved changes in this session.
```

**Comment by tsantalis** [comment]
You can use Eclipse IDE to open the workspace and import the Java project.
It's not enough just to physically place the project in the workspace. It should be imported and opened in the workspace.

**Comment by T45K** [comment]
I have already imported and opened the project.
![スクリーンショット 2019-11-08 14 01 08](https://user-images.githubusercontent.com/38446259/68451068-abaaba80-0230-11ea-941e-c654fd6e2ad7.png)

Each project is physically placed in `/Users/my_name/git/jdeodorant`, `/Users/my_name/git/jdeodorant-commandline`, `/Users/my_name/eclipse-workspace/jfreechart`.

Thanks.

**Comment by tsantalis** [comment]
@T45K Please try to place and open jfreechart in the `runtime-workspace`
This is the workspace that is created when you Run JDeodorant as an Eclipse Application.

**Comment by T45K** [comment]
JDeodorant runs correctly.
Thanks a lot!
