### ISSUE TITLE
Cannot use JDeodorant Commandline tool on PARSE, PARSE_AND_ANALYZE, and ANALYZE_EXISITING command

### ISSUE THREAD

**Issue by Coppelian** [tsantalis/jdeodorant-commandline#18]
Hi @tsantalis,

**Issues**
I faced multiple bugs when I executed PARSE, PARSE_AND_ANALYZE, and ANALYZE_EXISITING, which reported back with java AST error and NullPointerException error.

**My objective**
I want to apply multiple refactoring opportunities on different projects from defects4j dataset in batch mode.
Those projects can be inspected using JDeodorant GUI in Eclipse, but cannot be executed using JDeodorant Commandline tool. I'll provide the dataset which could be used later.
I exported the JDeodorant Commandline tool following: Running as a standalone command-line application.
When I executed ./eclipse --help I can see the output. And when I execute ./eclipse -p 'myproject' -m print_opportunities, I can get responses.
I checked the repository and I want to execute analyze_existing command, it reports back with errors above.

**System environment**
- Ubuntu 22.04
- Environment: Eclipse 2019.12R
- Java version: openjdk 1.8
- JDeodorant version: 5.0.77
- JDeodorant Commandline version: print_opportunities
- Defects4j dataset version: v2.1.0

Can you inform me which is the fastest way to adopt all refactoring opportunities (e.g., god class, long method, feature envy, type checking) to multiple projects using the standalone command-line application?

**Comment by Coppelian** [comment]
To replicate bugs, please access this repository:
https://github.com/Coppelian/d4j_sf/tree/main
Following the readme file to load the dataset for testing.

**Comment by tsantalis** [comment]
@Coppelian 
Can you copy here the stacktrace of the java AST error and NullPointerException you are getting?

**Comment by Coppelian** [comment]
17:27:31.692 [main] INFO  c.c.j.e.commandline.Application - Project Codec-2 was found in the workspace
!SESSION 2024-10-01 17:27:30.858 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_422
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_CA
Framework arguments:  -p Codec-2 -m parse
Command-line arguments:  -os linux -ws gtk -arch x86_64 -consoleLog -p Codec-2 -m parse

!ENTRY org.eclipse.team.core 4 0 2024-10-01 17:27:31.695
!MESSAGE Could not instantiate provider org.eclipse.egit.core.GitProvider for project Codec-2.
!STACK 1
org.eclipse.team.core.TeamException: Could not instantiate provider org.eclipse.egit.core.GitProvider for project Codec-2.
	at org.eclipse.team.core.RepositoryProvider.mapNewProvider(RepositoryProvider.java:200)
	at org.eclipse.team.core.RepositoryProvider.mapExistingProvider(RepositoryProvider.java:267)
	at org.eclipse.team.core.RepositoryProvider.getProvider(RepositoryProvider.java:542)
	at org.eclipse.team.internal.core.TeamHookDispatcher.getProvider(TeamHookDispatcher.java:96)
	at org.eclipse.team.internal.core.TeamHookDispatcher.getRuleFactory(TeamHookDispatcher.java:102)
	at org.eclipse.core.internal.resources.Rules.factoryFor(Rules.java:101)
	at org.eclipse.core.internal.resources.Rules.modifyRule(Rules.java:155)
	at org.eclipse.core.internal.resources.Project.setDescription(Project.java:1241)
	at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:163)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
!SUBENTRY 1 org.eclipse.team.core 4 0 2024-10-01 17:27:31.696
!MESSAGE Could not instantiate provider org.eclipse.egit.core.GitProvider for project Codec-2.
java.lang.NullPointerException
	at java.io.File.<init>(File.java:279)
	at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:172)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

**Comment by Coppelian** [comment]
17:29:05.510 [main] INFO  c.c.j.e.commandline.Application - Project Compress-1 was found in the workspace
!SESSION 2024-10-01 17:29:02.834 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_422
java.vendor=Private Build
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_CA
Framework arguments:  -p Compress-1 -m parse
Command-line arguments:  -os linux -ws gtk -arch x86_64 -consoleLog -p Compress-1 -m parse

!ENTRY org.eclipse.team.core 4 0 2024-10-01 17:29:05.513
!MESSAGE Could not instantiate provider org.eclipse.egit.core.GitProvider for project Compress-1.
!STACK 1
org.eclipse.team.core.TeamException: Could not instantiate provider org.eclipse.egit.core.GitProvider for project Compress-1.
	at org.eclipse.team.core.RepositoryProvider.mapNewProvider(RepositoryProvider.java:200)
	at org.eclipse.team.core.RepositoryProvider.mapExistingProvider(RepositoryProvider.java:267)
	at org.eclipse.team.core.RepositoryProvider.getProvider(RepositoryProvider.java:542)
	at org.eclipse.team.internal.core.TeamHookDispatcher.getProvider(TeamHookDispatcher.java:96)
	at org.eclipse.team.internal.core.TeamHookDispatcher.getRuleFactory(TeamHookDispatcher.java:102)
	at org.eclipse.core.internal.resources.Rules.factoryFor(Rules.java:101)
	at org.eclipse.core.internal.resources.Rules.modifyRule(Rules.java:155)
	at org.eclipse.core.internal.resources.Project.setDescription(Project.java:1241)
	at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:163)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)
!SUBENTRY 1 org.eclipse.team.core 4 0 2024-10-01 17:29:05.514
!MESSAGE Could not instantiate provider org.eclipse.egit.core.GitProvider for project Compress-1.
java.lang.NullPointerException
	at java.io.File.<init>(File.java:279)
	at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:172)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1465)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1438)

=========================================================
I cannot replicate AST error, this is the execution of parse command.

**Comment by tsantalis** [comment]
@Coppelian 
You should create Eclipse projects that are successfully compiled and fully built, and give those as input to the tool.
Moreover, these projects should be open in the Eclipse workspace.

If you open the Eclipse IDE on the workspace that these projects are stored, you should see them imported and opened into the Package Explorer of Eclipse.

Based on what you said the following worked.
`./eclipse -p 'myproject' -m print_opportunities`

This means you have an open project named `myproject` in the target Eclipse workspace.

Also make sure to use the code of this branch (not the master branch)
https://github.com/tsantalis/jdeodorant-commandline/tree/print-opportunities

**Comment by Coppelian** [comment]
@tsantalis Thank you for your response.
I'm using the print-opportunities branch.

These defects4j projects can be compiled using ant compile and ant compile.tests. 
However, the project cannot be tested due to the bug inside, which means I cannot generate jar files for these projects. This might not meet the requirement of 'fully built'.
I'm not sure if this condition will affect the results from JDeodorant.

I've tested these projects using JDeodorant GUI, which works when producing identification and refactoring that was shown in the video.
I've had to copy the workspace of Eclipse IDE to the exported command line eclipse workspace to 'open the project in the workspace'.

It seems that there are problems within my setup above.

Can you respond to these questions:
- Does JDeodorant commandline tool requires fully build, including running all tests? If tests failed, does it affect the refactoring?
- Does copying the workspace affect the execution of exported JDeodorant commandline tool?
- Does JDeodorant commandline tool supports directly applying all refactoring opportunities to projects, and which command should I use?

Thank you.

**Comment by tsantalis** [comment]
You should generate an Eclipse project for each project in the workspace.
I know how to do it with Maven and Gradle, but I am not sure how it is done with Ant.

`mvn eclipse:eclipse`
`gradlew eclipse`

I found this article about Ant and Eclipse, which might be helpful.
https://www.oreilly.com/library/view/eclipse-cookbook/0596007108/ch07s03.html
