### ISSUE TITLE
NullPointerException in ExtractCloneRefactoringGapHanlder

### ISSUE THREAD

**Issue by alwaqfi** [tsantalis/jdeodorant-commandline#8]
Hi,

There is an error generated (details are below).

Note: This error is generated for JRuby - NiCad_Blind - Case 753 from the files on Prof. Nikolaos website.

Regards,
Asif

10:45:30.317 [main] INFO  c.c.j.e.commandline.Application - 88%: Reading information from row 2909 (Clone group ID 753, clone 5)
10:45:30.346 [main] INFO  c.c.j.e.commandline.Application - 88%: Generating PDG for method "setUp" in "org.jruby.test.TestLoadService"
10:45:32.229 [main] INFO  c.c.j.e.commandline.Application - 88%: Analyzing Clone 1 (Group 753, Pair 1-5): org.jruby.test.TestRequire#setUp (row 2905) and org.jruby.test.TestLoadService#setUp (row 2909)
10:45:32.300 [main] INFO  c.c.j.e.commandline.Application - CDT 1 depth = 0, CDT 2 depth = 0
10:45:32.300 [main] INFO  c.c.j.e.commandline.Application - CDT 1 leaves = 1, CDT 2 leaves = 1
java.lang.NullPointerException
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoringGapHandler.differenceBelongsToBlockGaps(ExtractCloneRefactoringGapHandler.java:306)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoringGapHandler.createArgument(ExtractCloneRefactoringGapHandler.java:904)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.createArgument(ExtractCloneRefactoring.java:3985)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.generateGetterMethodInvocation(ExtractCloneRefactoring.java:4098)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.processASTNodeWithDifferences(ExtractCloneRefactoring.java:3437)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.processCloneStructureNode(ExtractCloneRefactoring.java:2938)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.extractClone(ExtractCloneRefactoring.java:1254)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.apply(ExtractCloneRefactoring.java:341)
    at gr.uom.java.jdeodorant.refactoring.manipulators.ExtractCloneRefactoring.checkFinalConditions(ExtractCloneRefactoring.java:5058)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.testRefactoring(Application.java:969)
    at ca.concordia.jdeodorant.eclipse.commandline.Application.start(Application.java:208)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

**Comment by tsantalis** [comment]
Fixed in commit [e4151db005280658690034b836336d714be4ee19](https://github.com/tsantalis/JDeodorant/commit/e4151db005280658690034b836336d714be4ee19)
